<?php

/* 
 * Copyright (C) 2015 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
?>
<?php echo '<?php'; ?>

namespace <?= $this->fieldsetNamespace ?>;

use Zend\Form\Fieldset;
use Zend\InputFilter\InputFilterProviderInterface;
use XelaxHTMLPurifier\Filter\HTMLPurifier;

use <?= $this->entityClass ?>;

/**
 * <?= $this->entityName ?> Fieldset
 */
class <?= $this->entityName ?>Fieldset extends <?= empty($this->parentFieldset) ? 'Fieldset' : '\\'.$this->parentFieldset ?> implements InputFilterProviderInterface{

	public function __construct($name = "", $options = array()){
		if($name == ""){
			$name = '<?= $this->entityName ?>Fieldset';
		}
		parent::__construct($name, $options);
	}

	public function init(){
		parent::init();
		$this->setObject(new <?= $this->entityName ?>());

<?php
			foreach($this->fields as $field){
				if($field['id']){
					continue;
				}
				echo $this->partial('formfield.phtml', array('field' => $field));
			}
		?>
	}

	public function getInputFilterSpecification() {
		$filters = array(
<?php
			foreach($this->fields as $field){
				if($field['id']){
					continue;
				}
				echo $this->partial('formfilter.phtml', array('field' => $field));
			}
		?>
		);
<?php 
		if(!empty($this->parentFieldset)) :  ?>
		$filters = array_merge(parent::getInputFilterSpecification(), $filters);
<?php 
		endif; ?>
		return $filters;
	}
}
