<?php

/* 
 * Copyright (C) 2015 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$type = strtolower($this->field['type']);

$template = 'text';
if(strpos($type, 'datetime') !== false){
	$template = 'datetime';
} elseif(strpos($type, 'time') !== false){
	$template = 'time';
} elseif(strpos($type, 'date') !== false){
	$template = 'date';
} elseif(strpos($type, 'int') !== false){
	$template = 'integer';
} elseif(strpos($type, 'float') !== false || strpos($type, 'double') !== false){
	$templtate = 'float';
} elseif(strpos($type, 'boolean') !== false){
	$template = 'switch';
} elseif(strpos($type, 'text') !== false){
	$template = 'textarea';
}

echo $this->partial('formfilters/'.$template, array('field' => $this->field));
